export const DataShowFile = [
  {
    folio: 1,
    expediente: "Cary",
    estado: "Pendiente",
    encargado: "Mirelle",
  },
  {
    folio: 2,
    expediente: "Ileana",
    estado: "Cancelado",
    encargado: "Brion",
  },
  {
    folio: 3,
    expediente: "Baldwin",
    estado: "Activo",
    encargado: "Beverie",
  },
  {
    folio: 4,
    expediente: "Stinky",
    estado: "Pendiente",
    encargado: "Charo",
  },
  {
    folio: 5,
    expediente: "Debby",
    estado: "Cancelado",
    encargado: "Shalom",
  },
  {
    folio: 6,
    expediente: "Javier",
    estado: "Pendiente",
    encargado: "Monti",
  },
  {
    folio: 7,
    expediente: "Cassi",
    estado: "Activo",
    encargado: "Jenny",
  },
  {
    folio: 8,
    expediente: "Burr",
    estado: "Cancelado",
    encargado: "Maryellen",
  },
  {
    folio: 9,
    expediente: "Alethea",
    estado: "Pendiente",
    encargado: "Delmore",
  },
  {
    folio: 10,
    expediente: "Amble",
    estado: "Pendiente",
    encargado: "Marshal",
  },
  {
    folio: 11,
    expediente: "Margaret",
    estado: "Cancelado",
    encargado: "Kelvin",
  },
  {
    folio: 12,
    expediente: "Linda",
    estado: "Pendiente",
    encargado: "Ola",
  },
  {
    folio: 13,
    expediente: "Goldia",
    estado: "Cancelado",
    encargado: "Buckie",
  },
  {
    folio: 14,
    expediente: "Odo",
    estado: "Pendiente",
    encargado: "Jobi",
  },
  {
    folio: 15,
    expediente: "Robbie",
    estado: "Cancelado",
    encargado: "Cristin",
  },
  {
    folio: 16,
    expediente: "Russ",
    estado: "Cancelado",
    encargado: "Aksel",
  },
  {
    folio: 17,
    expediente: "Joli",
    estado: "Activo",
    encargado: "Syd",
  },
  {
    folio: 18,
    expediente: "Lauren",
    estado: "Cancelado",
    encargado: "Chloette",
  },
  {
    folio: 19,
    expediente: "Jeramie",
    estado: "Activo",
    encargado: "Arlan",
  },
  {
    folio: 20,
    expediente: "Tobi",
    estado: "Cancelado",
    encargado: "Lotty",
  },
  {
    folio: 21,
    expediente: "Johnnie",
    estado: "Pendiente",
    encargado: "Kelwin",
  },
  {
    folio: 22,
    expediente: "Flo",
    estado: "Pendiente",
    encargado: "Mic",
  },
  {
    folio: 23,
    expediente: "Cissiee",
    estado: "Pendiente",
    encargado: "Dawna",
  },
  {
    folio: 24,
    expediente: "Britney",
    estado: "Cancelado",
    encargado: "Willy",
  },
  {
    folio: 25,
    expediente: "Maryanne",
    estado: "Pendiente",
    encargado: "Devlin",
  },
  {
    folio: 26,
    expediente: "Erasmus",
    estado: "Cancelado",
    encargado: "Nolly",
  },
  {
    folio: 27,
    expediente: "Kirstin",
    estado: "Cancelado",
    encargado: "Maximilien",
  },
  {
    folio: 28,
    expediente: "Larine",
    estado: "Activo",
    encargado: "Conny",
  },
  {
    folio: 29,
    expediente: "Edi",
    estado: "Cancelado",
    encargado: "Rossie",
  },
  {
    folio: 30,
    expediente: "Ira",
    estado: "Activo",
    encargado: "Torre",
  },
  {
    folio: 31,
    expediente: "Reeta",
    estado: "Activo",
    encargado: "Glynnis",
  },
  {
    folio: 32,
    expediente: "Elsi",
    estado: "Pendiente",
    encargado: "Homer",
  },
  {
    folio: 33,
    expediente: "Daisey",
    estado: "Activo",
    encargado: "Constantia",
  },
  {
    folio: 34,
    expediente: "Enrika",
    estado: "Activo",
    encargado: "Casandra",
  },
  {
    folio: 35,
    expediente: "L;urette",
    estado: "Activo",
    encargado: "Teresina",
  },
  {
    folio: 36,
    expediente: "Arne",
    estado: "Pendiente",
    encargado: "Carmen",
  },
  {
    folio: 37,
    expediente: "Luigi",
    estado: "Pendiente",
    encargado: "Sibylle",
  },
  {
    folio: 38,
    expediente: "Keen",
    estado: "Activo",
    encargado: "Bradly",
  },
  {
    folio: 39,
    expediente: "Joel",
    estado: "Pendiente",
    encargado: "Nannette",
  },
  {
    folio: 40,
    expediente: "Raynard",
    estado: "Cancelado",
    encargado: "Dasha",
  },
  {
    folio: 41,
    expediente: "Becka",
    estado: "Cancelado",
    encargado: "Mamie",
  },
  {
    folio: 42,
    expediente: "Alistair",
    estado: "Activo",
    encargado: "Livvyy",
  },
  {
    folio: 43,
    expediente: "Fulton",
    estado: "Pendiente",
    encargado: "Constancy",
  },
  {
    folio: 44,
    expediente: "Felic",
    estado: "Cancelado",
    encargado: "Winne",
  },
  {
    folio: 45,
    expediente: "Hagan",
    estado: "Activo",
    encargado: "Stevie",
  },
  {
    folio: 46,
    expediente: "Flss",
    estado: "Pendiente",
    encargado: "Danit",
  },
  {
    folio: 47,
    expediente: "Dana",
    estado: "Cancelado",
    encargado: "Massimo",
  },
  {
    folio: 48,
    expediente: "Dennis",
    estado: "Pendiente",
    encargado: "Ethel",
  },
  {
    folio: 49,
    expediente: "Brew",
    estado: "Cancelado",
    encargado: "Nanine",
  },
  {
    folio: 50,
    expediente: "Mira",
    estado: "Pendiente",
    encargado: "Elfreda",
  },
  {
    folio: 51,
    expediente: "Tobi",
    estado: "Pendiente",
    encargado: "Granthem",
  },
  {
    folio: 52,
    expediente: "Persis",
    estado: "Pendiente",
    encargado: "Agneta",
  },
  {
    folio: 53,
    expediente: "Rosalie",
    estado: "Activo",
    encargado: "Levin",
  },
  {
    folio: 54,
    expediente: "Keely",
    estado: "Pendiente",
    encargado: "Dmitri",
  },
  {
    folio: 55,
    expediente: "Rhodie",
    estado: "Cancelado",
    encargado: "Niall",
  },
  {
    folio: 56,
    expediente: "Jillana",
    estado: "Activo",
    encargado: "Roze",
  },
  {
    folio: 57,
    expediente: "Mohammed",
    estado: "Pendiente",
    encargado: "Tony",
  },
  {
    folio: 58,
    expediente: "Dore",
    estado: "Pendiente",
    encargado: "Sheba",
  },
  {
    folio: 59,
    expediente: "Thor",
    estado: "Pendiente",
    encargado: "Jeramie",
  },
  {
    folio: 60,
    expediente: "Alvinia",
    estado: "Cancelado",
    encargado: "Leif",
  },
  {
    folio: 61,
    expediente: "Freddie",
    estado: "Cancelado",
    encargado: "Nan",
  },
  {
    folio: 62,
    expediente: "Dukie",
    estado: "Pendiente",
    encargado: "Leena",
  },
  {
    folio: 63,
    expediente: "Casie",
    estado: "Pendiente",
    encargado: "Hyacinth",
  },
  {
    folio: 64,
    expediente: "Jilli",
    estado: "Pendiente",
    encargado: "Arlin",
  },
  {
    folio: 65,
    expediente: "Mal",
    estado: "Activo",
    encargado: "Beltran",
  },
  {
    folio: 66,
    expediente: "Jill",
    estado: "Cancelado",
    encargado: "Dieter",
  },
  {
    folio: 67,
    expediente: "Kipper",
    estado: "Activo",
    encargado: "Bartram",
  },
  {
    folio: 68,
    expediente: "Price",
    estado: "Cancelado",
    encargado: "Inger",
  },
  {
    folio: 69,
    expediente: "Pia",
    estado: "Activo",
    encargado: "Margy",
  },
  {
    folio: 70,
    expediente: "Austin",
    estado: "Pendiente",
    encargado: "Moyra",
  },
  {
    folio: 71,
    expediente: "Bianka",
    estado: "Activo",
    encargado: "Wesley",
  },
  {
    folio: 72,
    expediente: "Joceline",
    estado: "Activo",
    encargado: "Johan",
  },
  {
    folio: 73,
    expediente: "Giffie",
    estado: "Pendiente",
    encargado: "Cordie",
  },
  {
    folio: 74,
    expediente: "Robina",
    estado: "Activo",
    encargado: "Svend",
  },
  {
    folio: 75,
    expediente: "Katharina",
    estado: "Activo",
    encargado: "Charmane",
  },
  {
    folio: 76,
    expediente: "Martelle",
    estado: "Activo",
    encargado: "Jarrad",
  },
  {
    folio: 77,
    expediente: "Nathan",
    estado: "Cancelado",
    encargado: "Christopher",
  },
  {
    folio: 78,
    expediente: "Rob",
    estado: "Pendiente",
    encargado: "Obie",
  },
  {
    folio: 79,
    expediente: "Liesa",
    estado: "Pendiente",
    encargado: "Jacquenetta",
  },
  {
    folio: 80,
    expediente: "Camile",
    estado: "Activo",
    encargado: "Kakalina",
  },
  {
    folio: 81,
    expediente: "Nobie",
    estado: "Cancelado",
    encargado: "Ricky",
  },
  {
    folio: 82,
    expediente: "Erasmus",
    estado: "Pendiente",
    encargado: "Liv",
  },
  {
    folio: 83,
    expediente: "Kore",
    estado: "Pendiente",
    encargado: "Kaitlynn",
  },
  {
    folio: 84,
    expediente: "Bernarr",
    estado: "Cancelado",
    encargado: "Devin",
  },
  {
    folio: 85,
    expediente: "Ly",
    estado: "Cancelado",
    encargado: "Bevin",
  },
  {
    folio: 86,
    expediente: "Dur",
    estado: "Pendiente",
    encargado: "Gabriellia",
  },
  {
    folio: 87,
    expediente: "Pat",
    estado: "Cancelado",
    encargado: "Griffy",
  },
  {
    folio: 88,
    expediente: "Florance",
    estado: "Pendiente",
    encargado: "Katheryn",
  },
  {
    folio: 89,
    expediente: "Ivonne",
    estado: "Cancelado",
    encargado: "Rani",
  },
  {
    folio: 90,
    expediente: "Ashia",
    estado: "Cancelado",
    encargado: "Danella",
  },
  {
    folio: 91,
    expediente: "Magnum",
    estado: "Cancelado",
    encargado: "Oralle",
  },
  {
    folio: 92,
    expediente: "Wilhelmina",
    estado: "Activo",
    encargado: "Dun",
  },
  {
    folio: 93,
    expediente: "Giralda",
    estado: "Cancelado",
    encargado: "Joachim",
  },
  {
    folio: 94,
    expediente: "Wilhelmina",
    estado: "Cancelado",
    encargado: "Dredi",
  },
  {
    folio: 95,
    expediente: "Konstantine",
    estado: "Pendiente",
    encargado: "Colline",
  },
  {
    folio: 96,
    expediente: "Wenonah",
    estado: "Activo",
    encargado: "Aleda",
  },
  {
    folio: 97,
    expediente: "Noel",
    estado: "Activo",
    encargado: "Terese",
  },
  {
    folio: 98,
    expediente: "Sergent",
    estado: "Pendiente",
    encargado: "Reuven",
  },
  {
    folio: 99,
    expediente: "Darleen",
    estado: "Activo",
    encargado: "Odella",
  },
  {
    folio: 100,
    expediente: "Joni",
    estado: "Activo",
    encargado: "Vincent",
  }
];
